### ISSUE TITLE
Piping from another stream.

### ISSUE THREAD

**Issue by yaroslavvoloshchuk-codaio** [extrabacon/xlrd-parser#2]
Is it possible to parse raw data from another stream (file upload from formidable), without saving it to disk? If not, maybe you can give an advice how it can be implemented? Thanks.

**Comment by extrabacon** [comment]
No, not in the current state. But it is definitely doable, since xlrd supports mmap. We could stream the data into stdin, into a Python mmap. That would be a great addition.

Let me know what you think.

Nicolas

**Comment by yaroslavvoloshchuk-codaio** [comment]
Thanks for answer! I dont work previously with mmap, can you give a simple example?

**Comment by extrabacon** [comment]
Sorry, I am an absolute Python beginner and have never used mmap. I saw that it can be used as an alternative to a file path in the xlrd documentation.

Nicolas

**Comment by yaroslavvoloshchuk-codaio** [comment]
Okay, whatever, thanks for your advice)
